"use client";
import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Code2, Eye, Maximize2, X } from "lucide-react";
import type { VM } from "@stackblitz/sdk";

interface LivePreviewProps {
  files: Record<string, string>;
  projectName: string;
}

export default function LivePreview({ files, projectName }: LivePreviewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<"preview" | "code">("preview");
  const [activeFile, setActiveFile] = useState("app/page.tsx");
  const [fullscreen, setFullscreen] = useState(false);
  const vmRef = useRef<VM | null>(null);

  useEffect(() => {
    let mounted = true;

    async function initStackBlitz() {
      try {
        const sdk = (await import("@stackblitz/sdk")).default;

        if (!containerRef.current || !mounted) return;

        const pkgJson = files["package.json"]
          ? JSON.parse(files["package.json"])
          : {
              name: projectName.toLowerCase().replace(/\s+/g, "-"),
              version: "0.1.0",
              private: true,
              scripts: { dev: "next dev" },
              dependencies: {
                next: "14.2.5",
                react: "^18",
                "react-dom": "^18",
                "framer-motion": "^11",
                "lucide-react": "^0.400.0",
              },
              devDependencies: {
                typescript: "^5",
                tailwindcss: "^3.4.0",
                autoprefixer: "^10.0.1",
                postcss: "^8",
              },
            };

        // StackBlitz doesn't support 'nextjs' as template — use node + scripts
        const vm = await sdk.embedProject(
          containerRef.current,
          {
            title: projectName,
            description: "Generated by HackForge",
            template: "node",
            files: {
              ...files,
              "next.config.js":
                files["next.config.js"] ||
                `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;`,
              "postcss.config.js":
                files["postcss.config.js"] ||
                `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };`,
              "package.json": JSON.stringify(pkgJson, null, 2),
            },
          },
          {
            height: "100%",
            width: "100%",
            hideNavigation: false,
            forceEmbedLayout: true,
            openFile: "app/page.tsx",
            view: "preview",
            startScript: "dev",
          }
        );

        vmRef.current = vm;
        setLoading(false);
      } catch (err) {
        console.error("StackBlitz failed to load:", err);
        setLoading(false);
      }
    }

    initStackBlitz();
    return () => {
      mounted = false;
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Apply file updates to existing VM
  useEffect(() => {
    if (vmRef.current) {
      vmRef.current.applyFsDiff({ destroy: [], create: files });
    }
  }, [files]);

  const codeFiles = Object.keys(files).filter((f) => !f.endsWith(".ico"));

  return (
    <div
      className={`flex flex-col ${
        fullscreen ? "fixed inset-0 z-50 bg-void-black" : "h-full"
      }`}
    >
      {/* Toolbar */}
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-glass-border bg-void-deep/60 backdrop-blur-sm">
        <div className="flex items-center gap-1 rounded-lg bg-void-deep/80 border border-glass-border p-1">
          <button
            onClick={() => setActiveTab("preview")}
            className={`flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-display font-semibold transition-all ${
              activeTab === "preview"
                ? "bg-accent-cerulean/20 text-accent-cerulean"
                : "text-text-muted hover:text-text-secondary"
            }`}
          >
            <Eye className="w-3 h-3" /> Preview
          </button>
          <button
            onClick={() => setActiveTab("code")}
            className={`flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-display font-semibold transition-all ${
              activeTab === "code"
                ? "bg-accent-cerulean/20 text-accent-cerulean"
                : "text-text-muted hover:text-text-secondary"
            }`}
          >
            <Code2 className="w-3 h-3" /> Code
          </button>
        </div>

        {activeTab === "code" && (
          <div className="flex items-center gap-1 overflow-x-auto flex-1">
            {codeFiles.map((f) => (
              <button
                key={f}
                onClick={() => setActiveFile(f)}
                className={`px-2.5 py-1 rounded text-[10px] font-mono whitespace-nowrap transition-all ${
                  activeFile === f
                    ? "bg-accent-cerulean/20 text-accent-cerulean"
                    : "text-text-muted hover:text-text-secondary"
                }`}
              >
                {f.split("/").pop()}
              </button>
            ))}
          </div>
        )}

        <div className="ml-auto">
          <button
            onClick={() => setFullscreen(!fullscreen)}
            className="p-1.5 rounded-lg border border-glass-border text-text-muted hover:text-text-primary transition-colors"
          >
            {fullscreen ? (
              <X className="w-3.5 h-3.5" />
            ) : (
              <Maximize2 className="w-3.5 h-3.5" />
            )}
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 relative overflow-hidden">
        <div
          ref={containerRef}
          className={`absolute inset-0 ${
            activeTab === "preview" ? "block" : "hidden"
          }`}
          style={{ background: "#0a0a12" }}
        />

        {activeTab === "code" && (
          <div className="h-full overflow-auto bg-void-deep/80 p-6">
            <pre className="text-xs font-mono text-text-secondary leading-relaxed whitespace-pre-wrap break-words">
              <code>{files[activeFile] || "// File not yet generated"}</code>
            </pre>
          </div>
        )}

        <AnimatePresence>
          {loading && activeTab === "preview" && (
            <motion.div
              initial={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 flex flex-col items-center justify-center bg-void-deep/90 backdrop-blur-sm z-10"
            >
              <div className="flex flex-col items-center gap-4">
                <div className="relative w-12 h-12">
                  <div className="absolute inset-0 rounded-full border-2 border-accent-cerulean/20 animate-ping" />
                  <div className="absolute inset-2 rounded-full border-2 border-accent-cerulean animate-spin border-t-transparent" />
                </div>
                <p className="text-sm font-display text-text-secondary">
                  Spinning up StackBlitz...
                </p>
                <p className="text-xs text-text-muted">Live preview loading</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
